### ISSUE TITLE
Ansible fails with custom rsa keyfile

### ISSUE THREAD

**Issue by Lewiscowles1986** [chriso0710/pikiosk#5]
`ansible.cfg` needs to be updated or command line switches passed in with custom username or private key file. Suggest adding troubleshooting section to readme.md or adding wiki page with link in readme.md

**Comment by Lewiscowles1986** [comment]
changes that worked (for me)

```shell
cat >> ansible.cfg << ANSIBLE_CFG
private_key_file = ~/.ssh/2016_4096_rsa
remote_user = kiosk-admin
ANSIBLE_CFG

```

**Comment by chriso0710** [comment]
Thanks. Yes, this should be added to the readme.

**Comment by Lewiscowles1986** [comment]
Should I combine with #6 and commit once?
