### ISSUE TITLE
Chrome profile lock after changing hostname

### ISSUE THREAD

**Issue by chriso0710** [chriso0710/pikiosk#8]
> The profile appears to be in use by another Google Chrome process (16053) on another computer (raspberry).  Chrome has locked the profile so that it doesn't get corrupted.  If you are sure no other processes are using this profile, you can unlock the profile and relaunch Chrome.

See https://bugs.chromium.org/p/chromium/issues/detail?id=367048

Remove chromium lock with

`rm -rf ~/.config/chromium/Singleton*`

after changing hostname worked for me. Should be a task in Ansible.

**Comment by Lewiscowles1986** [comment]
This is in https://github.com/CODESIGN2/rpi-pixel-kiosk/blob/master/home/pi/start-kiosk.sh, perhaps we could share that script so that the convention for stopping screensaver also persists?

**Comment by chriso0710** [comment]
Yes, I plan to include the `rm` in the playbook.
